### ISSUE TITLE
serverless.ymlのpackage: excludeが効いてない

### ISSUE THREAD

**Issue by sinofseven** [serverless-japan/forum#2]
serverless.ymlにGLOB形式で以下のように書くと、  
デプロイパッケージにserverless.ymlが含まれ、```node_modules/aws-sdk/```以下のファイルは除外できると思うのですが、  
Lambdaからデプロイパッケージを取得して確認してみると、serverless.ymlは含まれるのですが、```node_modules/aws-sdk/```以下のファイルが含まれてました。
```yaml
package:
  include:
    - serverless.yml
  exclude:
    - node_modules/aws-sdk/**
```

自分がどこか書き間違えてるのでしょうか、それともバグなのでしょうか?  

serverless: v1.17.0

**Comment by horike37** [comment]
書き込みありがとうございます！
うーん、ぱっと見、問題はなさそうな気がします。一度@sinofsevenさんが使用されているserverless.yml全体を見せてもらうことはできますか？

僕の環境でも試してみようと思います。

**Comment by sinofseven** [comment]
```yaml
service: imagemagick

frameworkVersion: ">=1.13.1 <2.0.0"

custom:
  region: ap-northeast-1
  bookmarkletKey: xxxxxxxxxxxxx
  faultline:
    apiKey: "xxxxxxxxxxxxxxxxxx"
    endpoint: "xxxxxxxxxxxxxxxxx"

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-northeast-1
  stage: test
  timeout: 120
  memorySize: 256
  cfLogs: true
  apiKey: false
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"
    - Effect: Allow
      Action:
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
      Resource:
        - "arn:aws:logs:*:*:*"
    - Effect: Allow
      Action:
        - "s3:*"
      Resource:
        - "*"

package:
  include:
    - serverless.yml
    - src/**
  exclude:
    - .git/**
    - vendor/**
    - doc/**
    - node_modules/aws-sdk/**

functions:
  test:
    handler: src/index.handler
  identify:
    handler: src/identify.handler
  image:
    handler: src/image.handler
    events:
      - http:
          path: image
          method: get
          integration: lambda-proxy
  info:
    handler: src/info.handler
    memorySize: 1024
    events:
      - http:
          path: info
          method: post
          integration: lambda-proxy
  redirect:
    handler: src/redirect.handler
    events:
      - http:
          path: redirect
          method: get
          integration: lambda-proxy
```
認証情報だけ書き換えてますが、使ったserverless.ymlです。
