### ISSUE TITLE
Variable.jsのパラメータの上書き機能において 'cron(0 0 * * ? *)' というような括弧を含む文字列を利用されることが想定されていない

### ISSUE THREAD

**Issue by k1LoW** [serverless-japan/forum#4]
serverless.ymlで

```yaml
provider:
  name: aws
  runtime: nodejs6.10
  environment:
    LAMBDA_SCHEDULE: ${env:LAMBDA_SCHEDULE, 'cron(0 0 * * ? *)'}
functions:
    cronFunc:
        handler: handler.cronFunc
        events:
           - schedule:
              rate: ${self:provider.environment.LAMBDA_SCHEDULE}
              enabled: true
```

というように

- Lambda Functionの `schedule` に環境変数を渡したいが、デフォルト値として 'cron(0 0 * * ? *)'

だと、うまくパースされないみたいです。

---

ちなみに回避策としては

```yaml
provider:
  name: aws
  runtime: nodejs6.10
  environment:
    LAMBDA_SCHEDULE_DEFAULT: 'cron(0 0 * * ? *)'
    LAMBDA_SCHEDULE: ${env:LAMBDA_SCHEDULE, self:provider.environment.LAMBDA_SCHEDULE_DEFAULT}
functions:
    cronFunc:
        handler: handler.cronFunc
        events:
           - schedule:
              rate: ${self:provider.environment.LAMBDA_SCHEDULE}
              enabled: true
```

という形で複雑なパースを回避すればなんとかなります。
