### ISSUE TITLE
functionsで生成されるS3バケットARNをResourcesから参照したい

### ISSUE THREAD

**Issue by keitakn** [serverless-japan/forum#8]
# 解決したい事

```
functions:
  myFunction:
    handler: dist/app/function/index.myFunction
    warmup: true
    events:
      - s3:
          bucket: myBucketName
          event: s3:ObjectCreated:*
```

このように関数を定義すると自動的にS3Bucketが作成されます。

しかしここで生成される予定のBucketARNをResourcesで作成したKinesisFirehoseの `BucketARN` に指定すると以下のエラーが発生します。

```
  Serverless Error ---------------------------------------

  An error occurred: AccountApiKinesisFirehose - S3 Bucket myBucketName does not exist. (Service: AmazonKinesisFirehose; Status Code: 400; Error Code: InvalidArgumentException; Request ID: 9862e9ed-1586-4ccf-9812-4b78df73f521).
```

ResourcesからmyFunctionが裏側で生成したBucket名が取れると良いのですが、上手くいきませんでした。

何か良い方法があれば教えて頂けると助かります🙇

```
resources:
  Resources:
    FirehoseRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: FirehoseRole
        AssumeRolePolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - firehose.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
        - PolicyName: FirehoseToS3Policy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - s3:AbortMultipartUpload
                  - s3:GetBucketLocation
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:ListBucketMultipartUploads
                  - s3:PutObject
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
    MyAthenaQueryResultsBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Delete
      Properties:
        BucketName: myQueryResults
    MyKinesisFirehoseLogGroup:
      Type: "AWS::Logs::LogGroup"
      Properties:
        LogGroupName: /aws/kinesisfirehose/MyDeliveryStream
    MyKinesisFirehoseLogStream:
      Type: "AWS::Logs::LogStream"
      Properties:
        LogGroupName:
          Ref: MyKinesisFirehoseLogGroup
        LogStreamName: S3Delivery
    MyKinesisFirehose:
      Type: AWS::KinesisFirehose::DeliveryStream
      Properties:
        DeliveryStreamName: MyDeliveryStream
        S3DestinationConfiguration:
          # ↓この部分をmyFunctionで定義されているBucket名にしたい
          BucketARN: arn:aws:s3:::myBucketName
          BufferingHints:
            IntervalInSeconds: '60'
            SizeInMBs: '5'
          CloudWatchLoggingOptions:
            Enabled: true
            LogGroupName:
              Ref: MyKinesisFirehoseLogGroup
            LogStreamName:
              Ref: MyKinesisFirehoseLogStream
          CompressionFormat: 'UNCOMPRESSED'
          RoleARN: { Fn::GetAtt: [ FirehoseRole, Arn ] }
```

※ ちなみに最終的にやりたい事は [Firehoseで出力したファイルをAthenaのパーティション形式に変換するLambda](https://qiita.com/sonodar/items/19dbd8fe6740d26d054a) にあるようにS3（myBucketName）にアップロードされたファイルをAthenaのパーティション形式であるHiveフォーマットに変換する事です。
